import Head from 'next/head';
import Image from 'next/image';
import localFont from 'next/font/local';
import styles from '@/styles/Home.module.css';
import axios, { AxiosResponse } from 'axios';
import { useState } from 'react';
import { ENDPOINT } from '@/constants';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export default function Home() {
  const [result, setResult] = useState<number>();

  const handleClick = async () => {
    const res: AxiosResponse<{ resultInt: number }> = await axios.get<{
      resultInt: number;
    }>(ENDPOINT);
    setResult(res.data.resultInt);
  };

  const onReset = () => setResult(undefined);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js logo"
            width={180}
            height={38}
            priority
          />
          <ul>
            <li>
              {`Click the 'Send Request' Button and check the request result below.`}
            </li>
            <li>Request Result: {result}</li>
          </ul>

          <div className={styles.ctas}>
            <a className={styles.primary} onClick={handleClick}>
              Send Request
            </a>
            <a className={styles.secondary} onClick={onReset}>
              Reset
            </a>
          </div>
        </main>
      </div>
    </>
  );
}
